<%
require_relative 'libraries/helpers'
DuoOpenvpnBuild::Helpers.configure!(token: ENV['PACKAGECLOUD_TOKEN'])
%>

suites:
  - name: default
    run_list: duo-openvpn-build::default
    attributes:
      duo_openvpn_build:
        version: <%= DuoOpenvpnBuild::Helpers.version %>
        revision: <%= DuoOpenvpnBuild::Helpers.revision %>
        packagecloud_token: <%= ENV['PACKAGECLOUD_TOKEN'] || 'test' %>
        publish_artifacts: <%= ENV['TRAVIS_PULL_REQUEST'] == 'false' ? true : false %>
